# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Title in Config.yml
email: your-email@domain.com
description: "Description in Config.yml"
baseurl: "/JekyllJournal" # the subpath of your site, e.g. /blog
url: "https://lalew.github.io" # the base hostname & protocol for your site
tagline: "Tagline in Config.yml"

# Build settings
markdown: kramdown
# Prevents turning headings into IDs
kramdown:
  auto_ids: false

# Pagination Settings (Multiple pages)
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'

# Link via Post Title instead of by Post's Filename
#   For "Posts" not "Pages"
permalink: /blog/:title
# /:categories/:year/:month/:day/:title/
# permalink: pretty

